import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { getCheckoutQueue, processCheckout, getVisitDocuments } from '../../api/checkout';
import { getVisitTypeFees } from '../../api/settings';

const DARK  = '#0A2540';
const TEAL  = '#0D9488'; // checkout accent

// ─── Visit type label ────────────────────────────────────────────────
function fmtVisitType(t) {
  if (!t) return 'General Visit';
  return t.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('-');
}

function fmtDate(d) {
  if (!d) return '—';
  return new Date(d + 'T00:00:00').toLocaleDateString('en-JM', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' });
}

function fmtJMD(n) {
  return `J$${Number(n ?? 0).toLocaleString('en-JM', { minimumFractionDigits: 2 })}`;
}

// ─── Icons ────────────────────────────────────────────────────────────
function Ico({ d, size = 16 }) {
  return <svg width={size} height={size} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75}><path strokeLinecap="round" strokeLinejoin="round" d={d} /></svg>;
}
const IcoCash      = () => <Ico d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />;
const IcoPlus      = () => <Ico size={12} d="M12 4v16m8-8H4" />;
const IcoX         = () => <Ico size={12} d="M6 18L18 6M6 6l12 12" />;
const IcoCheck     = () => <Ico size={20} d="M5 13l4 4L19 7" />;
const IcoFlask     = () => <Ico size={14} d="M9 3h6m-6 0H7a1 1 0 00-1 1v2.172a2 2 0 00.586 1.414l4.828 4.828A2 2 0 0112 14v5m0-5v5m0 0h1a1 1 0 001-1v-1a1 1 0 00-1-1h-2a1 1 0 00-1 1v1a1 1 0 001 1h1" />;
const IcoImg       = () => <Ico size={14} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />;
const IcoCert      = () => <Ico size={14} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />;
const IcoPill      = () => <Ico size={14} d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z" />;
const IcoCal       = () => <Ico size={14} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />;
const IcoDl        = () => <Ico size={13} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />;
const IcoShield    = () => <Ico size={14} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />;

// ─── Section header ───────────────────────────────────────────────────
function SectionHead({ icon, label, color, count }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 10 }}>
      <div style={{ width: 26, height: 26, borderRadius: 8, background: color + '18', display: 'flex', alignItems: 'center', justifyContent: 'center', color, flexShrink: 0 }}>{icon}</div>
      <span style={{ fontSize: 11, fontWeight: 700, color, textTransform: 'uppercase', letterSpacing: '0.7px' }}>{label}</span>
      {count != null && count > 0 && <span style={{ fontSize: 10, fontWeight: 700, background: color + '18', color, borderRadius: 20, padding: '1px 6px' }}>{count}</span>}
    </div>
  );
}

// ─── Printable download helper ────────────────────────────────────────
function printSection(title, content) {
  const win = window.open('', '_blank', 'width=700,height=900');
  win.document.write(`
    <html><head><title>${title} — Seymour Doctors & Associates</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 32px; color: #0F172A; font-size: 13px; }
      h1 { font-size: 18px; margin-bottom: 4px; }
      .sub { color: #64748B; font-size: 12px; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      th { text-align: left; font-size: 11px; color: #64748B; padding: 6px 8px; border-bottom: 2px solid #E2E8F0; text-transform: uppercase; letter-spacing: 0.5px; }
      td { padding: 8px 8px; border-bottom: 1px solid #F1F5F9; vertical-align: top; }
      .footer { margin-top: 40px; border-top: 1px solid #E2E8F0; padding-top: 16px; font-size: 11px; color: #94A3B8; }
    </style></head><body>
    <h1>${title}</h1>
    <div class="sub">Seymour Doctors & Associates — Generated ${new Date().toLocaleDateString('en-JM', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
    ${content}
    <div class="footer">This document was generated by PulseOS. Please retain for your records.</div>
    </body></html>
  `);
  win.document.close();
  win.focus();
  win.print();
}

// ─── Queue card ───────────────────────────────────────────────────────
function QueueCard({ visit, selected, onClick }) {
  const [hov, setHov] = useState(false);
  const name = `${visit.patient_first_name} ${visit.patient_last_name}`;
  return (
    <div onClick={onClick} onMouseEnter={() => setHov(true)} onMouseLeave={() => setHov(false)}
      style={{ padding: '13px 15px', borderRadius: 10, border: `1.5px solid ${selected ? DARK : hov ? '#CBD5E1' : '#EEF2F7'}`, background: selected ? '#F0F9FF' : hov ? '#FAFBFC' : '#FFFFFF', cursor: 'pointer', transition: 'all 0.14s' }}>
      <div style={{ fontSize: 13, fontWeight: 700, color: '#0F172A', marginBottom: 2 }}>{name}</div>
      <div style={{ fontSize: 11, color: '#64748B' }}>{fmtVisitType(visit.visit_type)} · Dr. {visit.doctor_last_name}</div>
      {visit.follow_up_required === 1 && (
        <div style={{ fontSize: 10, fontWeight: 600, color: '#059669', marginTop: 4, display: 'flex', alignItems: 'center', gap: 4 }}>
          <span style={{ width: 5, height: 5, borderRadius: '50%', background: '#059669', display: 'inline-block' }} />
          Follow-up requested
        </div>
      )}
    </div>
  );
}

// ─── Line item row ────────────────────────────────────────────────────
function LineItemRow({ item, fees, onChange, onRemove }) {
  return (
    <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 7 }}>
      <input list="fee-descriptions" value={item.description} onChange={e => {
        const desc = e.target.value;
        const matched = fees.find(f => f.visit_type === desc);
        onChange({ description: desc, amount_jmd: matched ? matched.fee_jmd : item.amount_jmd });
      }} placeholder="Service description"
        style={{ flex: 1, padding: '7px 10px', borderRadius: 7, border: '1px solid #E2E8F0', fontSize: 12, color: '#0F172A', outline: 'none', boxSizing: 'border-box' }} />
      <datalist id="fee-descriptions">{fees.map(f => <option key={f.visit_type} value={f.visit_type} />)}</datalist>
      <input type="number" min="0" value={item.amount_jmd} onChange={e => onChange({ ...item, amount_jmd: e.target.value })} placeholder="0.00"
        style={{ width: 110, padding: '7px 10px', borderRadius: 7, border: '1px solid #E2E8F0', fontSize: 12, color: '#0F172A', outline: 'none', boxSizing: 'border-box', textAlign: 'right' }} />
      <button onClick={onRemove} style={{ background: '#FFF1F2', border: 'none', color: '#E11D48', cursor: 'pointer', padding: '6px 7px', borderRadius: 7, display: 'flex', alignItems: 'center' }}><IcoX /></button>
    </div>
  );
}

// ─── Insurance row ────────────────────────────────────────────────────
function InsuranceRow({ label, provider, approved, onProviderChange, onApprovedChange, color }) {
  return (
    <div style={{ background: color + '08', border: `1px solid ${color}25`, borderRadius: 10, padding: '12px 14px', marginBottom: 10 }}>
      <div style={{ fontSize: 10, fontWeight: 700, color, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 8 }}>{label}</div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 130px', gap: 8 }}>
        <div>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#475569', marginBottom: 4 }}>Provider</div>
          <input value={provider} onChange={e => onProviderChange(e.target.value)} placeholder="e.g. Sagicor"
            style={{ width: '100%', padding: '7px 10px', borderRadius: 7, border: '1px solid #E2E8F0', fontSize: 12, color: '#0F172A', outline: 'none', background: '#FFF', boxSizing: 'border-box' }} />
        </div>
        <div>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#475569', marginBottom: 4 }}>Approved (J$)</div>
          <input type="number" min="0" value={approved} onChange={e => onApprovedChange(e.target.value)} placeholder="0.00"
            style={{ width: '100%', padding: '7px 10px', borderRadius: 7, border: '1px solid #E2E8F0', fontSize: 12, color: '#0F172A', outline: 'none', background: '#FFF', boxSizing: 'border-box', textAlign: 'right' }} />
        </div>
      </div>
    </div>
  );
}

// ─── Receipt modal ────────────────────────────────────────────────────
function ReceiptModal({ checkout, visit, onClose }) {
  const name = `${visit.patient_first_name} ${visit.patient_last_name}`;
  return (
    <div style={{ position: 'fixed', inset: 0, zIndex: 400, background: 'rgba(15,23,42,0.45)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ background: '#FFFFFF', borderRadius: 16, padding: 32, width: 400, boxShadow: '0 20px 60px rgba(0,0,0,0.18)', maxHeight: '90vh', overflowY: 'auto' }}>
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <div style={{ width: 52, height: 52, borderRadius: '50%', background: '#F0FDF4', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 12px', color: '#059669' }}><IcoCheck /></div>
          <div style={{ fontSize: 16, fontWeight: 800, color: '#0F172A', marginBottom: 4 }}>Checkout Complete</div>
          <div style={{ fontSize: 12, color: '#94A3B8' }}>Receipt #{checkout.receipt_reference}</div>
        </div>
        <div style={{ background: '#F8FAFC', borderRadius: 10, padding: '12px 14px', marginBottom: 16 }}>
          <div style={{ fontSize: 11, fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 6 }}>Patient</div>
          <div style={{ fontSize: 13, fontWeight: 600, color: '#0F172A' }}>{name}</div>
          <div style={{ fontSize: 11, color: '#94A3B8', marginTop: 2 }}>{fmtVisitType(visit.visit_type)}</div>
        </div>
        {checkout.line_items?.length > 0 && (
          <div style={{ marginBottom: 16 }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 8 }}>Services</div>
            {checkout.line_items.map((li, i) => (
              <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0', borderBottom: i < checkout.line_items.length - 1 ? '1px solid #F1F5F9' : 'none' }}>
                <span style={{ fontSize: 12, color: '#475569' }}>{li.description}</span>
                <span style={{ fontSize: 12, fontWeight: 600, color: '#0F172A' }}>{fmtJMD(li.amount_jmd)}</span>
              </div>
            ))}
          </div>
        )}
        <div style={{ borderTop: '2px solid #F1F5F9', paddingTop: 12, marginBottom: 20 }}>
          {Number(checkout.insurance_amount_approved) > 0 && (
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
              <span style={{ fontSize: 12, color: '#64748B' }}>Insurance credit{checkout.insurance_provider ? ` (${checkout.insurance_provider})` : ''}</span>
              <span style={{ fontSize: 12, color: '#059669', fontWeight: 600 }}>- {fmtJMD(checkout.insurance_amount_approved)}</span>
            </div>
          )}
          <div style={{ display: 'flex', justifyContent: 'space-between' }}>
            <span style={{ fontSize: 13, fontWeight: 700, color: '#0F172A' }}>Patient Balance</span>
            <span style={{ fontSize: 15, fontWeight: 800, color: DARK }}>{fmtJMD(checkout.patient_balance)}</span>
          </div>
          <div style={{ fontSize: 11, color: '#94A3B8', marginTop: 4 }}>Paid via {checkout.patient_payment_method ?? checkout.payment_type}</div>
        </div>
        <button onClick={onClose} style={{ width: '100%', padding: '11px 0', borderRadius: 10, background: DARK, border: 'none', color: '#FFFFFF', fontSize: 13, fontWeight: 700, cursor: 'pointer' }}>Done</button>
      </div>
    </div>
  );
}

// ─── Documents panel (tests, sick cert, prescriptions, follow-up) ─────
function VisitSummaryPanel({ visit, docs, token }) {
  const navigate = useNavigate();
  if (!docs) return <div style={{ fontSize: 12, color: '#94A3B8', padding: '12px 0' }}>Loading visit documents…</div>;

  const { otc = [], sick_certs = [], investigations = [], imaging = [], prescriptions = [], follow_up } = docs;
  const hasTests = investigations.length + imaging.length > 0;
  const hasRx    = prescriptions.length > 0;
  const hasSick  = sick_certs.length > 0;
  const hasFollowUp = follow_up?.follow_up_required === 1;
  const hasAny   = hasTests || hasRx || hasSick || hasFollowUp || otc.length > 0;

  if (!hasAny) return (
    <div style={{ background: '#F8FAFC', borderRadius: 12, padding: '14px 16px', marginBottom: 20, border: '1px solid #F1F5F9', fontSize: 12, color: '#94A3B8' }}>
      No tests, prescriptions, or documents attached to this visit.
    </div>
  );

  const dlTests = () => {
    const rows = [
      ...investigations.map(i => `<tr><td>${i.test_name}</td><td>${i.category ?? '—'}</td><td><strong>${i.priority}</strong></td><td style="color:#64748B">${i.status}</td></tr>`),
      ...imaging.map(i => `<tr><td>${i.modality} — ${i.body_area}</td><td>Imaging</td><td><strong>${i.priority}</strong></td><td style="color:#64748B">${i.status}</td></tr>`),
    ].join('');
    printSection('Investigation & Imaging Requests', `
      <p>Patient: <strong>${visit.patient_first_name} ${visit.patient_last_name}</strong> &nbsp;|&nbsp; Dr. ${visit.doctor_last_name} &nbsp;|&nbsp; ${new Date().toLocaleDateString('en-JM')}</p>
      <table><thead><tr><th>Test / Study</th><th>Category</th><th>Priority</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table>
    `);
  };

  const dlRx = () => {
    const rows = prescriptions.map(p => `
      <tr>
        <td><strong>${p.drug_name}</strong></td>
        <td>${p.dosage} ${p.route ?? ''}</td>
        <td>${p.frequency}</td>
        <td>${p.duration_days ? p.duration_days + ' days' : '—'}</td>
        <td>${p.quantity ?? '—'}</td>
        <td>${p.nhf_covered ? 'Yes' : 'No'}</td>
      </tr>`).join('');
    printSection('Prescription', `
      <p>Patient: <strong>${visit.patient_first_name} ${visit.patient_last_name}</strong> &nbsp;|&nbsp; Dr. ${visit.doctor_last_name} &nbsp;|&nbsp; ${new Date().toLocaleDateString('en-JM')}</p>
      <table><thead><tr><th>Drug</th><th>Dosage / Route</th><th>Frequency</th><th>Duration</th><th>Qty</th><th>NHF</th></tr></thead><tbody>${rows}</tbody></table>
    `);
  };

  const dlSick = () => {
    const cert = sick_certs[0];
    printSection('Sick Certificate', `
      <p>This is to certify that <strong>${visit.patient_first_name} ${visit.patient_last_name}</strong> was examined and found unfit for <strong>${cert.unfit_for}</strong>.</p>
      <p><strong>Period:</strong> ${cert.date_unfit_from} to ${cert.date_unfit_to}</p>
      <p><strong>Diagnosis:</strong> ${cert.diagnosis ?? 'As discussed'}</p>
      <p><strong>Certificate Reference:</strong> ${cert.certificate_reference}</p>
      <p style="margin-top:40px">____________________________<br>Dr. ${visit.doctor_last_name}<br>Seymour Doctors & Associates</p>
    `);
  };

  const bookFollowUp = () => {
    const params = new URLSearchParams({ patient: visit.patient_id });
    if (follow_up?.follow_up_date) params.set('date', follow_up.follow_up_date);
    if (follow_up?.doctor_id) params.set('doctor', follow_up.doctor_id);
    navigate(`/receptionist/appointments/new?${params.toString()}`);
  };

  return (
    <div style={{ marginBottom: 20 }}>

      {/* Tests ordered */}
      {hasTests && (
        <div style={{ background: '#FAF5FF', border: '1px solid #E9D5FF', borderRadius: 12, padding: '14px 16px', marginBottom: 10 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
            <SectionHead icon={<IcoFlask />} label="Tests Ordered" color="#7C3AED" count={investigations.length + imaging.length} />
            <button onClick={dlTests} style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: 11, fontWeight: 700, color: '#7C3AED', background: '#EDE9FE', border: 'none', borderRadius: 7, padding: '5px 10px', cursor: 'pointer' }}>
              <IcoDl /> Print Form
            </button>
          </div>
          {investigations.map(i => (
            <div key={i.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '5px 0', borderBottom: '1px solid #F3E8FF' }}>
              <span style={{ fontSize: 12, color: '#0F172A', fontWeight: 500 }}>{i.test_name}</span>
              <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                <span style={{ fontSize: 10, fontWeight: 700, background: i.priority === 'urgent' ? '#FEF3C7' : '#F8FAFC', color: i.priority === 'urgent' ? '#92400E' : '#64748B', borderRadius: 20, padding: '1px 7px' }}>{i.priority}</span>
                <span style={{ fontSize: 10, color: '#94A3B8' }}>{i.category}</span>
              </div>
            </div>
          ))}
          {imaging.map(i => (
            <div key={i.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '5px 0', borderBottom: '1px solid #F3E8FF' }}>
              <span style={{ fontSize: 12, color: '#0F172A', fontWeight: 500 }}><IcoImg /> {i.modality} — {i.body_area}</span>
              <span style={{ fontSize: 10, fontWeight: 700, background: '#F8FAFC', color: '#64748B', borderRadius: 20, padding: '1px 7px' }}>{i.priority}</span>
            </div>
          ))}
        </div>
      )}

      {/* Prescriptions */}
      {hasRx && (
        <div style={{ background: '#F0FDF4', border: '1px solid #BBF7D0', borderRadius: 12, padding: '14px 16px', marginBottom: 10 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
            <SectionHead icon={<IcoPill />} label="Prescriptions" color="#059669" count={prescriptions.length} />
            <button onClick={dlRx} style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: 11, fontWeight: 700, color: '#059669', background: '#DCFCE7', border: 'none', borderRadius: 7, padding: '5px 10px', cursor: 'pointer' }}>
              <IcoDl /> Print
            </button>
          </div>
          {prescriptions.map(p => (
            <div key={p.id} style={{ padding: '6px 0', borderBottom: '1px solid #D1FAE5' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                <span style={{ fontSize: 13, fontWeight: 700, color: '#0F172A' }}>{p.drug_name}</span>
                <span style={{ fontSize: 10, color: '#64748B' }}>Qty: {p.quantity ?? '—'}</span>
              </div>
              <div style={{ fontSize: 11, color: '#475569', marginTop: 1 }}>{p.dosage} {p.route ? `· ${p.route}` : ''} · {p.frequency}{p.duration_days ? ` · ${p.duration_days} days` : ''}</div>
              {p.instructions && <div style={{ fontSize: 10, color: '#94A3B8', marginTop: 1 }}>{p.instructions}</div>}
              {p.nhf_covered && <span style={{ fontSize: 9, fontWeight: 700, background: '#D1FAE5', color: '#059669', borderRadius: 20, padding: '1px 6px', marginTop: 3, display: 'inline-block' }}>NHF Covered</span>}
            </div>
          ))}
        </div>
      )}

      {/* Sick certificate */}
      {hasSick && (
        <div style={{ background: '#FFFBEB', border: '1px solid #FDE68A', borderRadius: 12, padding: '14px 16px', marginBottom: 10 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
            <SectionHead icon={<IcoCert />} label="Sick Certificate" color="#D97706" />
            <button onClick={dlSick} style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: 11, fontWeight: 700, color: '#D97706', background: '#FEF3C7', border: 'none', borderRadius: 7, padding: '5px 10px', cursor: 'pointer' }}>
              <IcoDl /> Print
            </button>
          </div>
          {sick_certs.map(s => (
            <div key={s.id} style={{ fontSize: 12, color: '#0F172A' }}>
              <div>Unfit for <strong>{s.unfit_for}</strong> from {s.date_unfit_from} to {s.date_unfit_to}</div>
              {s.diagnosis && <div style={{ fontSize: 11, color: '#94A3B8', marginTop: 2 }}>{s.diagnosis}</div>}
              <div style={{ fontSize: 10, color: '#B45309', marginTop: 3 }}>Ref: {s.certificate_reference}</div>
            </div>
          ))}
        </div>
      )}

      {/* Follow-up */}
      {hasFollowUp && (
        <div style={{ background: '#F0F9FF', border: '1px solid #BAE6FD', borderRadius: 12, padding: '14px 16px', marginBottom: 10 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 }}>
            <SectionHead icon={<IcoCal />} label="Follow-Up Requested" color="#0369A1" />
            <button onClick={bookFollowUp}
              style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: 11, fontWeight: 700, color: '#0369A1', background: '#E0F2FE', border: 'none', borderRadius: 7, padding: '5px 10px', cursor: 'pointer' }}
              onMouseEnter={e => { e.currentTarget.style.background = '#BAE6FD'; }}
              onMouseLeave={e => { e.currentTarget.style.background = '#E0F2FE'; }}>
              <IcoCal /> Book in Calendar
            </button>
          </div>
          {follow_up.follow_up_date && (
            <div style={{ fontSize: 12, color: '#0F172A', fontWeight: 600 }}>Suggested date: {fmtDate(follow_up.follow_up_date)}</div>
          )}
          {follow_up.follow_up_notes && (
            <div style={{ fontSize: 11, color: '#475569', marginTop: 3 }}>{follow_up.follow_up_notes}</div>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Checkout form ────────────────────────────────────────────────────
const PAYMENT_METHODS = ['Cash', 'Card (Debit)', 'Card (Credit)', 'Bank Transfer', 'Cheque', 'NHF'];

function CheckoutForm({ visit, fees, token, onDone }) {
  const [payMethod, setPayMethod]           = useState('Cash');
  const [ins1Provider, setIns1Provider]     = useState(visit.patient_insurance_provider ?? '');
  const [ins1Approved, setIns1Approved]     = useState('0');
  const [showIns2, setShowIns2]             = useState(false);
  const [ins2Provider, setIns2Provider]     = useState('');
  const [ins2Approved, setIns2Approved]     = useState('0');
  const [hasInsurance, setHasInsurance]     = useState(!!visit.patient_insurance_provider);
  const [lineItems, setLineItems]           = useState(() => {
    if (visit.visit_type) {
      const matched = fees.find(f => f.visit_type === visit.visit_type);
      if (matched) return [{ description: fmtVisitType(matched.visit_type), amount_jmd: matched.fee_jmd }];
    }
    return [{ description: '', amount_jmd: '' }];
  });
  const [docs, setDocs]       = useState(null);
  const [saving, setSaving]   = useState(false);
  const [apiErr, setApiErr]   = useState('');
  const [receipt, setReceipt] = useState(null);

  useEffect(() => {
    if (!visit.visit_id || !token) return;
    getVisitDocuments(visit.visit_id, token)
      .then(r => setDocs(r.data?.data?.documents ?? {}))
      .catch(() => setDocs({}));
  }, [visit.visit_id, token]);

  const totalFee   = lineItems.reduce((s, i) => s + (Number(i.amount_jmd) || 0), 0);
  const ins1Amount = hasInsurance ? (Number(ins1Approved) || 0) : 0;
  const ins2Amount = hasInsurance && showIns2 ? (Number(ins2Approved) || 0) : 0;
  const totalIns   = ins1Amount + ins2Amount;
  const patientDue = Math.max(0, totalFee - totalIns);

  const addItem    = () => setLineItems(prev => [...prev, { description: '', amount_jmd: '' }]);
  const removeItem = (idx) => setLineItems(prev => prev.filter((_, i) => i !== idx));
  const updateItem = (idx, val) => setLineItems(prev => prev.map((item, i) => i === idx ? val : item));

  const submit = async () => {
    const validItems = lineItems.filter(i => i.description && Number(i.amount_jmd) > 0);
    if (validItems.length === 0) { setApiErr('Add at least one service line with a description and amount'); return; }
    setSaving(true); setApiErr('');
    try {
      const payType = hasInsurance ? (totalIns >= totalFee ? 'insurance' : 'mixed') : 'self_pay';
      const res = await processCheckout({
        visit_id:                   visit.visit_id,
        patient_id:                 visit.patient_id,
        payment_type:               payType,
        patient_payment_method:     payMethod,
        insurance_provider:         hasInsurance ? (ins1Provider || null) : null,
        insurance_amount_approved:  ins1Amount,
        insurance_provider_2:       hasInsurance && showIns2 ? (ins2Provider || null) : null,
        insurance_amount_approved_2: ins2Amount,
        total_fee:                  totalFee,
        line_items:                 validItems.map(i => ({ description: i.description, amount_jmd: Number(i.amount_jmd) })),
      }, token);
      setReceipt(res.data?.data?.checkout);
    } catch (e) {
      setApiErr(e.response?.data?.message ?? 'Checkout failed');
    } finally {
      setSaving(false);
    }
  };

  if (receipt) return <ReceiptModal checkout={receipt} visit={visit} onClose={onDone} />;

  return (
    <div style={{ overflowY: 'auto', padding: '0 0 40px' }}>

      {/* Patient header bar */}
      <div style={{ marginBottom: 20 }}>
        <div style={{ fontSize: 17, fontWeight: 800, color: '#0F172A', marginBottom: 2 }}>
          {visit.patient_first_name} {visit.patient_last_name}
        </div>
        <div style={{ fontSize: 12, color: '#64748B' }}>{fmtVisitType(visit.visit_type)} · Dr. {visit.doctor_last_name}</div>
      </div>

      {/* Visit documents: tests, rx, sick cert, follow-up */}
      <VisitSummaryPanel visit={visit} docs={docs} token={token} />

      <div style={{ height: 1, background: '#F1F5F9', marginBottom: 20 }} />

      {/* Services & Fees */}
      <div style={{ marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Services & Fees</div>
          <button onClick={addItem} style={{ display: 'flex', alignItems: 'center', gap: 5, background: 'none', border: '1px dashed #CBD5E1', borderRadius: 7, color: '#64748B', cursor: 'pointer', padding: '4px 9px', fontSize: 11, fontWeight: 600 }}>
            <IcoPlus /> Add line
          </button>
        </div>
        {lineItems.map((item, idx) => (
          <LineItemRow key={idx} item={item} fees={fees} onChange={val => updateItem(idx, val)} onRemove={() => removeItem(idx)} />
        ))}
      </div>

      <div style={{ height: 1, background: '#F1F5F9', marginBottom: 20 }} />

      {/* Payment method */}
      <div style={{ marginBottom: 16 }}>
        <div style={{ fontSize: 12, fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 8 }}>Payment Method</div>
        <div style={{ display: 'flex', gap: 7, flexWrap: 'wrap' }}>
          {PAYMENT_METHODS.map(m => (
            <button key={m} onClick={() => setPayMethod(m)}
              style={{ padding: '6px 13px', borderRadius: 20, fontSize: 12, fontWeight: 600, cursor: 'pointer', transition: 'all 0.12s', background: payMethod === m ? DARK : '#F8FAFC', color: payMethod === m ? '#FFFFFF' : '#64748B', border: `1px solid ${payMethod === m ? DARK : '#E2E8F0'}` }}>
              {m}
            </button>
          ))}
        </div>
      </div>

      {/* Insurance toggle */}
      <div style={{ marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: hasInsurance ? 12 : 0 }}>
          <button onClick={() => setHasInsurance(v => !v)}
            style={{ width: 36, height: 20, borderRadius: 10, border: 'none', background: hasInsurance ? '#0EA5E9' : '#E2E8F0', cursor: 'pointer', position: 'relative', transition: 'background 0.14s' }}>
            <span style={{ position: 'absolute', top: 2, left: hasInsurance ? 18 : 2, width: 16, height: 16, borderRadius: '50%', background: '#FFFFFF', transition: 'left 0.14s', boxShadow: '0 1px 3px rgba(0,0,0,0.2)' }} />
          </button>
          <span style={{ fontSize: 12, fontWeight: 600, color: '#475569' }}>Insurance / NHF contribution</span>
        </div>
        {hasInsurance && (
          <div>
            <InsuranceRow label="Primary Insurance" provider={ins1Provider} approved={ins1Approved} onProviderChange={setIns1Provider} onApprovedChange={setIns1Approved} color="#0EA5E9" />
            {showIns2
              ? <InsuranceRow label="Secondary Insurance" provider={ins2Provider} approved={ins2Approved} onProviderChange={setIns2Provider} onApprovedChange={setIns2Approved} color="#8B5CF6" />
              : (
                <button onClick={() => setShowIns2(true)}
                  style={{ display: 'flex', alignItems: 'center', gap: 5, background: 'none', border: '1px dashed #CBD5E1', borderRadius: 7, color: '#64748B', cursor: 'pointer', padding: '5px 10px', fontSize: 11, fontWeight: 600 }}>
                  <IcoShield /> Add secondary insurance
                </button>
              )
            }
          </div>
        )}
      </div>

      <div style={{ height: 1, background: '#F1F5F9', marginBottom: 20 }} />

      {/* Totals */}
      <div style={{ background: '#F8FAFC', borderRadius: 12, padding: '14px 16px', marginBottom: 20 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
          <span style={{ fontSize: 12, color: '#64748B' }}>Subtotal</span>
          <span style={{ fontSize: 12, fontWeight: 600, color: '#0F172A' }}>{fmtJMD(totalFee)}</span>
        </div>
        {ins1Amount > 0 && (
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
            <span style={{ fontSize: 12, color: '#64748B' }}>Primary insurance {ins1Provider ? `(${ins1Provider})` : ''}</span>
            <span style={{ fontSize: 12, fontWeight: 600, color: '#059669' }}>- {fmtJMD(ins1Amount)}</span>
          </div>
        )}
        {ins2Amount > 0 && (
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
            <span style={{ fontSize: 12, color: '#64748B' }}>Secondary insurance {ins2Provider ? `(${ins2Provider})` : ''}</span>
            <span style={{ fontSize: 12, fontWeight: 600, color: '#7C3AED' }}>- {fmtJMD(ins2Amount)}</span>
          </div>
        )}
        <div style={{ display: 'flex', justifyContent: 'space-between', paddingTop: 10, borderTop: '1px solid #E2E8F0', marginTop: 5 }}>
          <span style={{ fontSize: 14, fontWeight: 700, color: '#0F172A' }}>Patient Pays</span>
          <span style={{ fontSize: 18, fontWeight: 800, color: DARK }}>{fmtJMD(patientDue)}</span>
        </div>
      </div>

      {apiErr && <div style={{ fontSize: 12, color: '#E11D48', marginBottom: 14, padding: '10px 14px', background: '#FFF1F2', borderRadius: 8, border: '1px solid #FECDD3' }}>{apiErr}</div>}

      <button onClick={submit} disabled={saving}
        style={{ width: '100%', padding: '13px 0', borderRadius: 11, background: saving ? '#94A3B8' : TEAL, border: 'none', color: '#FFFFFF', fontSize: 14, fontWeight: 700, cursor: saving ? 'default' : 'pointer', transition: 'background 0.14s', boxShadow: saving ? 'none' : '0 4px 14px rgba(13,148,136,0.3)' }}>
        {saving ? 'Processing…' : `Collect ${fmtJMD(patientDue)}`}
      </button>
    </div>
  );
}

// ─── Main page ────────────────────────────────────────────────────────
export default function ReceptionistCheckout() {
  const { token, user } = useAuth();

  const [queue, setQueue]       = useState([]);
  const [fees, setFees]         = useState([]);
  const [selected, setSelected] = useState(null);
  const [loading, setLoading]   = useState(true);

  const loadQueue = () => {
    setLoading(true);
    getCheckoutQueue(token)
      .then(r => { setQueue(r.data?.data?.queue ?? []); setLoading(false); })
      .catch(() => setLoading(false));
  };

  useEffect(() => {
    if (!token) return;
    getVisitTypeFees(token).then(r => setFees(r.data?.data?.fees ?? [])).catch(() => {});
    loadQueue();
  }, [token]);

  const handleDone = () => { setSelected(null); loadQueue(); };

  const now = new Date();
  const hour = now.getHours();
  const greeting = hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening';

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>

      {/* ── Hero banner (matches dashboard "Good morning" style) ── */}
      <div style={{ background: DARK, padding: '20px 28px 0', flexShrink: 0, position: 'relative', overflow: 'hidden' }}>
        {/* decorative circles */}
        <div style={{ position: 'absolute', top: -50, right: -50, width: 220, height: 220, borderRadius: '50%', border: '40px solid rgba(13,148,136,0.09)', pointerEvents: 'none' }} />
        <div style={{ position: 'absolute', bottom: -30, right: 110, width: 110, height: 110, borderRadius: '50%', border: '22px solid rgba(13,148,136,0.05)', pointerEvents: 'none' }} />
        <div style={{ position: 'relative', zIndex: 1, display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', paddingBottom: 20 }}>
          <div>
            <div style={{ fontSize: 10, fontWeight: 700, color: 'rgba(13,148,136,0.8)', letterSpacing: '1.2px', textTransform: 'uppercase', marginBottom: 6 }}>
              Checkout
            </div>
            <div style={{ fontSize: 22, fontWeight: 800, color: '#FFFFFF', letterSpacing: '-0.4px', marginBottom: 5 }}>
              {greeting}, {user?.first_name ?? 'there'}
            </div>
            <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.4)', lineHeight: 1.5 }}>
              {loading ? 'Loading checkout queue…' : queue.length === 0 ? 'No visits awaiting checkout.' : `${queue.length} visit${queue.length !== 1 ? 's' : ''} awaiting checkout — select one to process`}
            </div>
          </div>
          {queue.length > 0 && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 12, background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 14, padding: '12px 18px', marginBottom: 4 }}>
              <span style={{ fontSize: 22, fontWeight: 800, color: '#FFFFFF' }}>{queue.length}</span>
              <span style={{ fontSize: 11, color: 'rgba(255,255,255,0.45)', fontWeight: 600 }}>in queue</span>
            </div>
          )}
        </div>
      </div>

      {/* ── Body ── */}
      <div style={{ flex: 1, display: 'flex', gap: 0, overflow: 'hidden' }}>

        {/* Queue sidebar */}
        <div style={{ width: 280, flexShrink: 0, borderRight: '1px solid #F1F5F9', overflowY: 'auto', padding: '16px 14px', display: 'flex', flexDirection: 'column', gap: 8, background: '#FAFBFC' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 2 }}>
            <span style={{ fontSize: 11, fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Queue</span>
            <button onClick={loadQueue} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 11, color: '#94A3B8', padding: 0 }}>Refresh</button>
          </div>
          {loading ? (
            <div style={{ fontSize: 12, color: '#94A3B8', textAlign: 'center', padding: '32px 0' }}>Loading…</div>
          ) : queue.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '48px 16px' }}>
              <div style={{ width: 40, height: 40, borderRadius: '50%', background: '#F0FDF4', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 10px', color: '#059669' }}><IcoCash /></div>
              <div style={{ fontSize: 12, fontWeight: 600, color: '#64748B', marginBottom: 3 }}>Queue is empty</div>
              <div style={{ fontSize: 11, color: '#94A3B8' }}>No completed visits awaiting checkout</div>
            </div>
          ) : queue.map(v => (
            <QueueCard key={v.visit_id} visit={v} selected={selected?.visit_id === v.visit_id} onClick={() => setSelected(v)} />
          ))}
        </div>

        {/* Checkout panel */}
        <div style={{ flex: 1, minWidth: 0, overflowY: 'auto', padding: '24px 28px', background: '#FFFFFF' }}>
          {!selected ? (
            <div style={{ height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
              <div style={{ width: 56, height: 56, borderRadius: '50%', background: '#F0FDFA', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 16, color: TEAL }}><IcoCash /></div>
              <div style={{ fontSize: 14, fontWeight: 700, color: '#64748B', marginBottom: 6 }}>Select a patient to process</div>
              <div style={{ fontSize: 12, color: '#94A3B8' }}>
                {queue.length === 0 ? 'No visits awaiting checkout.' : `${queue.length} visit${queue.length !== 1 ? 's' : ''} in the queue — select one to begin`}
              </div>
            </div>
          ) : (
            <CheckoutForm key={selected.visit_id} visit={selected} fees={fees} token={token} onDone={handleDone} />
          )}
        </div>
      </div>
    </div>
  );
}
